In [1]:
import pandas as pd 
import math

Game 1:
The player pays €5 and picks 3 letters (all lower case English letters) and 2 digits (numbers 0-9 inclusive). They win as follows:
What is correct	Prize
3 letters, both numbers	€100
Two letters, both numbers €50
One letter, both numbers €25
No letter, both numbers	€10

$$ p(100) = \frac{1}{26^3}  \times \frac{1}{100}  $$

$$ p(50) = 3 \times \frac{25}{26 ^ 3}   \times \frac{1}{100}  $$

$$ p(25) = 3 \times  \frac{25 ^ 2}{26 ^3} \times \frac{1}{100}   $$

$$ p(10) =  \frac {25^3}{26^3} \times \frac{1}{100}$$

In [2]:
plllnn = 1/26*1/26*1/26*1/100

In [3]:
df = pd.DataFrame({
    'prizes' : [100,50,25,10],
    'probabilities' : [
      1/(26**3) * 1/100, 
      3 * (25 / (26**3)) * 1 /100,
        3 * (25**2)  / (26**3) * 1/100,
        (25**3) / (26**3) * 1 /100
    ]
})

df

   prizes  probabilities
0     100   5.689577e-07
1      50   4.267183e-05
2      25   1.066796e-03
3      10   8.889964e-03

In [4]:
len(df['prizes'])

4

In [5]:
# for i in range(4):
#     print(i)

# Calculate the measures of central tendency

In [6]:
EV = 0
for i in range(len(df['prizes'])):
    EV += df['prizes'][i] * df['probabilities'][i]
    
print(f'Expected Value  : {EV:.3f}' )

Expected Value  : 0.118

$$ Expected Value \approx 0.118 $$

In [7]:
mean = df.mean()
print(f'the mean of the probabilities {mean.probabilities}')
mean

the mean of the probabilities 0.0025

prizes           46.2500
probabilities     0.0025
dtype: float64

In [8]:
df.describe()

           prizes  probabilities
count    4.000000   4.000000e+00
mean    46.250000   2.500000e-03
std     39.449335   4.288408e-03
min     10.000000   5.689577e-07
25%     21.250000   3.214611e-05
50%     37.500000   5.547337e-04
75%     62.500000   3.022588e-03
max    100.000000   8.889964e-03

In [9]:
def generatedletter():
    alphabets = list('abcdefgklmnopqrstuvwxyz')
    digits = [0,1,2,3,4,5,6,7,8,9]
generatedletter()

In [10]:
 win_data = [[100,1/26*1/26*1/26*1/10*1/10],
             [50,(1/26*1/26*1/10*1/10)+(1/26*25/26*1/10*1/10)+25/26*1/26*1/10],
             [25,1/26*1/10*1/10],
             [10,25/26*1/10*1/10]
            ]
    
expected_value = 0
for wins in win_data:
    expected_value += wins[0] * wins[1]
    print(f"Ex: {wins[0] * wins[1]}")
print(expected_value)
print(5- expected_value)

Ex: 5.689576695493856e-05
Ex: 0.20414201183431954
Ex: 0.009615384615384616
Ex: 0.09615384615384616
0.30996813837050524
4.690031861629495

# Game 2:
The player pays €5 and picks 3 letters (all lower case AND upper case English letters, repetition allowed). 
If they guess all correctly, they win €500,000

$$ p(500000) =  \frac {1^3}{52^3} \times \frac {1} {1}$$

In [11]:
plllLLL = 500000,1/52*1/52*1/52

In [12]:
df2 = pd.DataFrame({
    'prizes' : 5000000,
    'probabilities' : [1/(52**3) , 
    ]
})

df2

    prizes  probabilities
0  5000000       0.000007

In [13]:
len(df2['prizes'])

1

In [14]:
game = 500_000
win_data = [
    [500_000,1/52*1/52*1/52]
]

expected_value = 0
for wins in win_data:
    expected_value += wins[0] * wins[1]
    print(f"Ex: {wins[0] * wins[1]}")
print(expected_value)
print(5- expected_value)

Ex: 3.55598543468366
3.55598543468366
1.44401456531634

# Calculate the expected value for the club for both games.

In [16]:
print((5-expected_value))

1.44401456531634

# Create simulations of each game.

In [39]:
import random

In [19]:
def game(win=5_000_000):
    win_data = [
        [1/10_737_573],
        [100, 1/1_789_596],
        [50, 1/44_740],
        [25, 1/17_896],
        [10, 1/918],
        
    ]    
    random_num = random.random()
    cumulative_propability = 0
    for wins in win_data:
        cumulative_propability += wins[1]
        if cumulative_propability >= random_num:
            return wins[0]
    return 0

In [20]:
def game():
    letters = list('abcdefgklmnopqrstuvwxyzABCDEFGKLMNOPQRSTUVWXYZ')
    
    player_pick = [random.choice(letters) for _ in range(3)]
    
    draw = [random.choice(letters) for _ in range(3)]
    
    if player_pick == draw:
        return 500_000  # win
    else:
        return 0  # lose

In [21]:
game()

NameError: name 'random' is not defined

In [22]:
Calculate the measures of central tendency for each game, based off an appropriate number of simulations.

SyntaxError: invalid syntax (1859269763.py, line 1)

Calculate the measures of dispersion for each game, based off an appropriate number of simulations.

Discuss, in terms of those calculated statistics, which game you would recommend the club to adopt. [

In [1]:
1+1

2